language: emacs-lisp
addons:
  apt:
    packages:
      - gnutls-bin
      - libssl-dev
python:
  - "2.7"
before_install:
  - git submodule --quiet update --init
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - evm list
install:
  - pip install tornado
  - pip install jupyter==$JUPYTER
env:
  - EIN_TEST_TARGET=travis-ci-testein IPY_VERSION=0.13.2 EVM_EMACS=emacs-25.2-travis JUPYTER=1.0.0
  - EIN_TEST_TARGET=travis-ci-testein IPY_VERSION=0.13.2 EVM_EMACS=emacs-26.1-travis JUPYTER=1.0.0
matrix:
  allow_failures:
    # EMACS=emacs-snapshot
    - env: EIN_TEST_TARGET=travis-ci-testein IPY_VERSION=0.13.2 EMACS=emacs-snapshot
script:
  make $EIN_TEST_TARGET IPY_VERSION=$IPY_VERSION
