sudo: false
language: emacs-lisp

addons:
  apt:
    packages:
    - autogen

cache:
  directories:
  - $HOME/local
  - $HOME/.evm
  - $HOME/.cask

env:
  global:
    - PATH=$HOME/local/bin:$HOME/.cask/bin:$HOME/.evm/bin:$PATH
    - EIN_TEST_TARGET=travis-ci-testein
    - IPY_VERSION=0.13.2 
  matrix:
    - EVM_EMACS=emacs-25.2-travis
    - EVM_EMACS=emacs-26.1-travis

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-snapshot

before_script:
  - sudo sh tools/travis-gnutls.sh
  - gnutls-cli -v
  - |
    if [ ! -e $HOME/.cask/bin/cask ] || [ ! -e $HOME/.evm/bin/evm ] ; then
      curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
    fi
  - evm install $EVM_EMACS --use --skip
  - cask install

script:
  - emacs --version
  - make $EIN_TEST_TARGET IPY_VERSION=$IPY_VERSION
  - cask exec ert-runner