sudo: false
language: emacs-lisp

addons:
  apt:
    packages:
    - gnutls-bin

cache:
  directories:
  - $HOME/local

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH
    - EIN_TEST_TARGET=travis-ci-testein
    - IPY_VERSION=0.13.2 
  matrix:
    - EVM_EMACS=emacs-25.2-travis
    - EVM_EMACS=emacs-26.1-travis

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-snapshot

before_script:
  - gnutls-cli -v
  - sh tools/install-evm.sh
  - evm install $EVM_EMACS --use --skip
  - sh tools/install-cask.sh
  - cask install

script:
  - emacs --version
  - make $EIN_TEST_TARGET IPY_VERSION=$IPY_VERSION
  - cask exec ert-runner